/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post: operations["createOrganizationHierarchy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["getOrganization"];
        put: operations["updateOrganization"];
        post?: never;
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** @description Members may update their own notification preference; owner/admin role rules are enforced server-side. */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/organizations/{orgId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listEnvironments"];
        put?: never;
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        get: operations["getEnvironment"];
        put: operations["updateEnvironment"];
        post?: never;
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        get: operations["listMonitors"];
        put?: never;
        post: operations["createMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        get: operations["getMonitor"];
        put: operations["updateMonitor"];
        post?: never;
        delete: operations["deleteMonitor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/monitors/{monitorId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitorReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/incidents/{incidentId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acknowledgeIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/incidents/{incidentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{environmentId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Authorized durable refresh hints. Last-Event-ID replays at most 100 events; ordinary APIs remain the source of truth. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "owner" | "admin" | "member" | "viewer";
        /** @enum {string} */
        AssignableRole: "admin" | "member" | "viewer";
        AllowedActions: ("tenant:read" | "tenant:manage" | "members:read" | "members:invite" | "members:manage" | "monitors:read" | "monitors:manage" | "incidents:read" | "incidents:manage")[];
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            email_verified: boolean;
        };
        UserEnvelope: {
            user: components["schemas"]["User"];
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            session: {
                token: string;
                /** @enum {string} */
                token_type: "Bearer";
                /** Format: date-time */
                expires_at: string;
            };
        };
        Membership: {
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            user_id: string;
            role: components["schemas"]["Role"];
        };
        Member: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            incident_notifications_enabled: boolean;
            /** Format: date-time */
            created_at: string;
        };
        MemberList: {
            members: components["schemas"]["Member"][];
        };
        Invitation: {
            /** Format: uuid */
            organization_id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["AssignableRole"];
            /** Format: date-time */
            expires_at: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            role: components["schemas"]["Role"];
            allowed_actions: components["schemas"]["AllowedActions"];
            /** Format: date-time */
            created_at?: string;
        };
        OrganizationMutation: {
            name: string;
            slug?: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            description?: string;
            role: components["schemas"]["Role"];
            allowed_actions: components["schemas"]["AllowedActions"];
        };
        ProjectMutation: {
            name: string;
            description?: string;
        };
        Environment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            project_id: string;
            name: string;
            /** @enum {string} */
            type: "production" | "staging" | "development";
            role: components["schemas"]["Role"];
            allowed_actions: components["schemas"]["AllowedActions"];
        };
        DefaultOwnership: {
            organization: components["schemas"]["Organization"];
            membership: components["schemas"]["Membership"];
            project: components["schemas"]["Project"];
            environment: components["schemas"]["Environment"];
        };
        EnvironmentMutation: {
            name: string;
            /** @enum {string} */
            type: "production" | "staging" | "development";
        };
        MemberMutation: {
            role?: components["schemas"]["AssignableRole"];
            incident_notifications_enabled?: boolean;
        };
        Monitor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            environment_id: string;
            name: string;
            /** Format: uri */
            url: string;
            /** @enum {string} */
            method: "GET" | "HEAD";
            /** @enum {integer} */
            interval_seconds: 60 | 120 | 300 | 600 | 1800;
            timeout_seconds: number;
            expected_status_min: number;
            expected_status_max: number;
            version: number;
            paused: boolean;
            worker_pool_id: string;
            header_names: string[];
        };
        Check: {
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            job_type: "scheduled" | "manual";
            /** Format: date-time */
            scheduled_at: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string;
            succeeded: boolean;
            status_code?: number | null;
            error_category?: string | null;
            total_duration_us: number;
        };
        CheckPage: {
            items: components["schemas"]["Check"][];
            next_cursor?: string | null;
        };
        MonitorDetail: components["schemas"]["Monitor"] & {
            /** @enum {string} */
            state: "healthy" | "degraded" | "down" | "unknown";
            recent_checks: components["schemas"]["Check"][];
        };
        MonitorMutation: {
            name: string;
            /** Format: uri */
            url: string;
            /** @enum {string} */
            method?: "GET" | "HEAD";
            /** @enum {integer} */
            interval_seconds?: 60 | 120 | 300 | 600 | 1800;
            timeout_seconds?: number;
            expected_status_min?: number;
            expected_status_max?: number;
            headers?: {
                [key: string]: string;
            };
            worker_pool_id?: string;
        };
        Report: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            expected: number;
            observed: number;
            successful: number;
            unknown: number;
            observed_uptime?: number | null;
            coverage?: number | null;
            average_latency_ms?: number | null;
            fresh: boolean;
            /** Format: date-time */
            corrected_at?: string | null;
        };
        StateCounts: {
            healthy: number;
            degraded: number;
            down: number;
            unknown: number;
        };
        Dashboard: {
            states: components["schemas"]["StateCounts"];
            reliability: components["schemas"]["Report"];
            open_incidents: number;
            /** Format: date-time */
            generated_at: string;
        };
        Incident: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            environment_id: string;
            /** Format: uuid */
            monitor_id: string;
            /** @enum {string} */
            status: "open" | "resolved";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            acknowledged_at?: string | null;
            /** Format: uuid */
            acknowledged_by_user_id?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: uuid */
            resolved_by_user_id?: string | null;
            resolution_kind?: string | null;
            resolution_reason?: string | null;
        };
        IncidentEvent: {
            /** Format: uuid */
            id: string;
            type: string;
            /** Format: uuid */
            actor_user_id?: string | null;
            /** Format: uuid */
            source_job_id?: string | null;
            reason?: string | null;
            /** Format: date-time */
            occurred_at: string;
        };
        NotificationDelivery: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            transition: "opened" | "resolved";
            /** @enum {string} */
            state: "pending" | "leased" | "accepted" | "failed";
            attempts: number;
            /** Format: date-time */
            next_attempt_at: string;
            provider_status?: string | null;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            failed_at?: string | null;
        };
        IncidentSummary: {
            incident: components["schemas"]["Incident"];
            events: components["schemas"]["IncidentEvent"][];
            deliveries: components["schemas"]["NotificationDelivery"][];
        };
        IncidentPage: {
            items: components["schemas"]["Incident"][];
            next_cursor?: string | null;
        };
        Page: {
            items: Record<string, never>[];
            next_cursor?: string | null;
        };
        Error: {
            error: {
                code: string;
                message: string;
                request_id: string;
            };
        };
    };
    responses: {
        /** @description Access token response; refresh token is an HttpOnly SameSite=Strict cookie */
        Auth: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Stable safe error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bounded rate exceeded */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgId: string;
        MemberId: string;
        ProjectId: string;
        EnvironmentId: string;
        MonitorId: string;
        IncidentId: string;
        Limit: number;
        Cursor: string;
        From: string;
        To: string;
    };
    requestBodies: {
        Credentials: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        Token: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        OrganizationMutation: {
            content: {
                "application/json": components["schemas"]["OrganizationMutation"];
            };
        };
        ProjectMutation: {
            content: {
                "application/json": components["schemas"]["ProjectMutation"];
            };
        };
        EnvironmentMutation: {
            content: {
                "application/json": components["schemas"]["EnvironmentMutation"];
            };
        };
        MonitorMutation: {
            content: {
                "application/json": components["schemas"]["MonitorMutation"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Credentials"];
        responses: {
            201: components["responses"]["Auth"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Credentials"];
        responses: {
            200: components["responses"]["Auth"];
            401: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Auth"];
            401: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    all_sessions?: boolean;
                };
            };
        };
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Token"];
        responses: {
            /** @description Verified user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Accepted regardless of account existence */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password reset and sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Token"];
        responses: {
            /** @description Membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible organizations with effective role and allowed actions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organizations: components["schemas"]["Organization"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createOrganizationHierarchy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    organization: components["schemas"]["OrganizationMutation"];
                    project: components["schemas"]["ProjectMutation"];
                };
            };
        };
        responses: {
            /** @description Organization, owner membership, project, and production environment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultOwnership"];
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["OrganizationMutation"];
        responses: {
            /** @description Updated organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft deleted by owner */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberMutation"];
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["AssignableRole"];
                };
            };
        };
        responses: {
            /** @description Invitation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects?: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProjectMutation"];
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProjectMutation"];
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        environments?: components["schemas"]["Environment"][];
                    };
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EnvironmentMutation"];
        responses: {
            /** @description Environment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EnvironmentMutation"];
        responses: {
            /** @description Environment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty environment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    listMonitors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description At most 100 monitors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        monitors?: components["schemas"]["Monitor"][];
                    };
                };
            };
        };
    };
    createMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["MonitorMutation"];
        responses: {
            /** @description Monitor created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    getMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor state and recent checks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["MonitorMutation"];
        responses: {
            /** @description Monitor updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    deleteMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor soft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    testMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual check admitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        job_id: string;
                    };
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    pauseMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    resumeMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            403: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    listChecks: {
        parameters: {
            query: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                job_type?: "scheduled" | "manual";
            };
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable newest-first page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckPage"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    monitorReport: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
            };
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                monitorId: components["parameters"]["MonitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduled-only uptime, coverage, latency, and freshness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    dashboard: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
            };
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Polling reconstruction snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listIncidents: {
        parameters: {
            query: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                status?: "open" | "resolved";
            };
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable newest-first incident page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentPage"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incident, bounded timeline, and notification state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    acknowledgeIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Incident acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    resolveIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Incident manually resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                environmentId: components["parameters"]["EnvironmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream containing only event ID, type, resource_type, and resource_id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
}
